- job-template:
    name: 'gate-{name}-chef-unit'
    node: '{node}'

    wrappers:
      - build-timeout:
          timeout: 60
      - timestamps

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - chef-bundler-prep
      - chef-berkshelf-prep
      - chef-cookbook-chefspec

    publishers:
      - console-log

- job-template:
    name: 'gate-{name}-chef-lint'
    node: '{node}'

    wrappers:
      - build-timeout:
          timeout: 60
      - timestamps

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - chef-bundler-prep
      - chef-berkshelf-prep
      - chef-cookbook-foodcritic

    publishers:
      - console-log

- job-template:
    name: 'gate-{name}-chef-style'
    node: '{node}'

    wrappers:
      - build-timeout:
          timeout: 60
      - timestamps

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - chef-bundler-prep
      - chef-berkshelf-prep
      - chef-cookbook-rubocop

    publishers:
      - console-log

- job:
    name: gate-openstack-chef-repo
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          mkdir -p .cookbooks .bundle
          bundle config --global jobs $(nproc)
          bundle install --path=.bundle
          # Validates cookbooks
          bundle exec berks install --path=.cookbooks
          # Validates roles
          bundle exec spiceweasel infrastructure.yml --debug

    publishers:
      - console-log
