- job-template:
    name: 'periodic-tempest-dsvm-all{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 185
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=180
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_ALL=1
          export ZUUL_BRANCH={branch-override}
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic


- job-template:
    name: 'periodic-tempest-dsvm-coverage{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 185
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=180
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_COVERAGE=1
          export ZUUL_BRANCH={branch-override}
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic


- job-template:
    name: 'periodic-tempest-dsvm-stress{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 185
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=180
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_STRESS=1
          export ZUUL_BRANCH={branch-override}
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic


- job-group:
    name: devstack-periodic-jobs
    jobs:
      - '{pipeline}-tempest-dsvm-full{branch-designator}'
      - '{pipeline}-tempest-dsvm-postgres-full{branch-designator}'
      - '{pipeline}-tempest-dsvm-neutron{branch-designator}'
      - 'periodic-tempest-dsvm-all{branch-designator}'
      - 'periodic-tempest-dsvm-coverage{branch-designator}'
      - 'periodic-tempest-dsvm-stress{branch-designator}'
      - '{pipeline}-tempest-dsvm-neutron-pg{branch-designator}'
      - '{pipeline}-tempest-dsvm-large-ops{branch-designator}'
      - '{pipeline}-tempest-dsvm-neutron-large-ops{branch-designator}'
      - '{pipeline}-tempest-dsvm-savanna-full{branch-designator}'
      - '{pipeline}-tempest-dsvm-savanna-postgres-full{branch-designator}'
      - '{pipeline}-tempest-dsvm-savanna-neutron{branch-designator}'
      - '{pipeline}-devstack-dsvm-neutron{branch-designator}'
      - '{pipeline}-tempest-dsvm-ironic{branch-designator}'
      - '{pipeline}-tempest-dsvm-ironic-postgres{branch-designator}'
