- job:
    name: gate-noop
    node: precise

- job:
    name: gate-django_openstack_auth-noop
    node: precise

- job-template:
    name: 'gate-{name}-run-tests'

    builders:
      - gerrit-git-prep
      - run-tests:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - console-log

    node: '{node}'
