- job-template:
    name: 'check-rally-install-{node}'
    node: '{node}'

    builders:
      - link-logs
      - gerrit-git-prep
      - shell: "tests_ci/test_install.sh"

    publishers:
      - console-log
